---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install tox-travis

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOX_ENV=py27-ansible25
      dist: xenial
    - python: 2.7
      env: TOX_ENV=py27-ansible26
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
# script: travis_wait 30 tox --develop
script: tox -e $TOX_ENV
