---
- hosts: servers
  gather_facts: True
  become: True
  become_method: sudo
  # serial: True
  vars:
    boss__netdata__netdata_master_group_label: 'graphite_master'
    boss__netdata__netdata_graphite_ip: '192.168.50.105'
  pre_tasks:

  - debug: msg="{{ groups[boss__netdata__netdata_master_group_label] }}"
  - debug: msg="{{boss__netdata__netdata_graphite_ip}}:2003"
