---
- hosts: netdata_registry
  gather_facts: True
  become: yes
  become_method: sudo
  roles:
    - role: ../
      # graphite_secret_key: testtest123
      # version: 1.1.3
      # graphite_install_version: "{{ version }}"
      # graphite_cache_graphite_url: 'http://127.0.0.1:8080'
      # bossjones__user: vagrant
      # bossjones__group: vagrant
      boss__netdata__netdata_interface: 'enp0s8'

      netdata_registry_enabled: True
      netdata_registry_to_announce: "http://{{ netdata_stream_master_node }}:{{ netdata_default_port }}"
      pri_domain_name: scarlett-office.local
      netdata_stream_enabled: True
      # You can generate API keys, with the linux command: uuidgen
      netdata_stream_api_key: 3402645b-2dbd-40d7-b748-21f564813f2f
      netdata_stream_master_node: "{{boss__netdata__netdata_master_ip}}"
      nginx_listen_port: 8080

- hosts: netdata_nodes
  gather_facts: True
  become: yes
  become_method: sudo
  roles:
    - role: ../
      boss__netdata__netdata_interface: 'enp0s8'
      netdata_registry_enabled: False
      netdata_registry_to_announce: "http://{{ netdata_stream_master_node }}:{{ netdata_default_port }}"
      pri_domain_name: scarlett-office.local
      netdata_stream_enabled: True
      # You can generate API keys, with the linux command: uuidgen
      netdata_stream_api_key: 3402645b-2dbd-40d7-b748-21f564813f2f
      netdata_stream_master_node: "{{boss__netdata__netdata_master_ip}}"
      nginx_listen_port: 8080
